// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: session/session-service.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Username struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Username) Reset() {
	*x = Username{}
	mi := &file_session_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Username) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Username) ProtoMessage() {}

func (x *Username) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Username.ProtoReflect.Descriptor instead.
func (*Username) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *Username) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConnectionCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionCredentials) Reset() {
	*x = ConnectionCredentials{}
	mi := &file_session_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionCredentials) ProtoMessage() {}

func (x *ConnectionCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionCredentials.ProtoReflect.Descriptor instead.
func (*ConnectionCredentials) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionCredentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_session_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ConnectedAt,proto3" json:"ConnectedAt,omitempty"`
	LastSeenTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=LastSeenTime,proto3" json:"LastSeenTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_session_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Session) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *Session) GetLastSeenTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenTime
	}
	return nil
}

var File_session_session_service_proto protoreflect.FileDescriptor

const file_session_session_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsession/session-service.proto\x12\x0fsession_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1e\n" +
	"\bUsername\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"I\n" +
	"\x15ConnectionCredentials\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Token\x18\x02 \x01(\tR\x05Token\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"\xcf\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bIsActive\x18\x03 \x01(\bR\bIsActive\x12<\n" +
	"\vConnectedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vConnectedAt\x12>\n" +
	"\fLastSeenTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fLastSeenTime2\xdc\x01\n" +
	"\x0eSessionService\x12>\n" +
	"\aConnect\x12\x19.session_service.Username\x1a\x16.session_service.Token\"\x00\x12E\n" +
	"\n" +
	"Disconnect\x12\x19.session_service.Username\x1a\x1a.google.protobuf.BoolValue\"\x00\x12C\n" +
	"\vVerifyToken\x12\x16.session_service.Token\x1a\x1a.google.protobuf.BoolValue\"\x00B4Z2github.com/Abelova-Grupa/Mercypher/proto/sessionpbb\x06proto3"

var (
	file_session_session_service_proto_rawDescOnce sync.Once
	file_session_session_service_proto_rawDescData []byte
)

func file_session_session_service_proto_rawDescGZIP() []byte {
	file_session_session_service_proto_rawDescOnce.Do(func() {
		file_session_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_session_service_proto_rawDesc), len(file_session_session_service_proto_rawDesc)))
	})
	return file_session_session_service_proto_rawDescData
}

var file_session_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_session_session_service_proto_goTypes = []any{
	(*Username)(nil),              // 0: session_service.Username
	(*ConnectionCredentials)(nil), // 1: session_service.ConnectionCredentials
	(*Token)(nil),                 // 2: session_service.Token
	(*Session)(nil),               // 3: session_service.Session
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),  // 5: google.protobuf.BoolValue
}
var file_session_session_service_proto_depIdxs = []int32{
	4, // 0: session_service.Session.ConnectedAt:type_name -> google.protobuf.Timestamp
	4, // 1: session_service.Session.LastSeenTime:type_name -> google.protobuf.Timestamp
	0, // 2: session_service.SessionService.Connect:input_type -> session_service.Username
	0, // 3: session_service.SessionService.Disconnect:input_type -> session_service.Username
	2, // 4: session_service.SessionService.VerifyToken:input_type -> session_service.Token
	2, // 5: session_service.SessionService.Connect:output_type -> session_service.Token
	5, // 6: session_service.SessionService.Disconnect:output_type -> google.protobuf.BoolValue
	5, // 7: session_service.SessionService.VerifyToken:output_type -> google.protobuf.BoolValue
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_session_session_service_proto_init() }
func file_session_session_service_proto_init() {
	if File_session_session_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_session_service_proto_rawDesc), len(file_session_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_session_service_proto_goTypes,
		DependencyIndexes: file_session_session_service_proto_depIdxs,
		MessageInfos:      file_session_session_service_proto_msgTypes,
	}.Build()
	File_session_session_service_proto = out.File
	file_session_session_service_proto_goTypes = nil
	file_session_session_service_proto_depIdxs = nil
}
