// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: session/session-service.proto

package sessionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_session_session_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserID) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	APIAdress     string                 `protobuf:"bytes,2,opt,name=APIAdress,proto3" json:"APIAdress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLocation) Reset() {
	*x = UserLocation{}
	mi := &file_session_session_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLocation) ProtoMessage() {}

func (x *UserLocation) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLocation.ProtoReflect.Descriptor instead.
func (*UserLocation) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserLocation) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserLocation) GetAPIAdress() string {
	if x != nil {
		return x.APIAdress
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_session_session_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{2}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifiedToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifiedToken) Reset() {
	*x = VerifiedToken{}
	mi := &file_session_session_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedToken) ProtoMessage() {}

func (x *VerifiedToken) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedToken.ProtoReflect.Descriptor instead.
func (*VerifiedToken) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{3}
}

func (x *VerifiedToken) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type LastSeen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastSeen) Reset() {
	*x = LastSeen{}
	mi := &file_session_session_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSeen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSeen) ProtoMessage() {}

func (x *LastSeen) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSeen.ProtoReflect.Descriptor instead.
func (*LastSeen) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{4}
}

func (x *LastSeen) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LastSeen) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ConnectedAt,proto3" json:"ConnectedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_session_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_session_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_session_service_proto_rawDescGZIP(), []int{5}
}

func (x *Session) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Session) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Session) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Session) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

var File_session_session_service_proto protoreflect.FileDescriptor

const file_session_session_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsession/session-service.proto\x12\x0fsession_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\" \n" +
	"\x06UserID\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"D\n" +
	"\fUserLocation\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x1c\n" +
	"\tAPIAdress\x18\x02 \x01(\tR\tAPIAdress\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\rVerifiedToken\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"R\n" +
	"\bLastSeen\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12.\n" +
	"\x04Time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04Time\"\x8b\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bIsActive\x18\x03 \x01(\bR\bIsActive\x12<\n" +
	"\vConnectedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vConnectedAt2\x8d\a\n" +
	"\x0eSessionService\x12T\n" +
	"\x12CreateUserLocation\x12\x1d.session_service.UserLocation\x1a\x1d.session_service.UserLocation\"\x00\x12K\n" +
	"\x0fGetUserLocation\x12\x17.session_service.UserID\x1a\x1d.session_service.UserLocation\"\x00\x12T\n" +
	"\x12UpdateUserLocation\x12\x1d.session_service.UserLocation\x1a\x1d.session_service.UserLocation\"\x00\x12G\n" +
	"\x12DeleteUserLocation\x12\x17.session_service.UserID\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x0eCreateLastSeen\x12\x19.session_service.LastSeen\x1a\x19.session_service.LastSeen\"\x00\x12C\n" +
	"\vGetLastSeen\x12\x17.session_service.UserID\x1a\x19.session_service.LastSeen\"\x00\x12H\n" +
	"\x0eUpdateLastSeen\x12\x19.session_service.LastSeen\x1a\x19.session_service.LastSeen\"\x00\x12C\n" +
	"\x0eDeleteLastSeen\x12\x17.session_service.UserID\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\vCreateToken\x12\x17.session_service.UserID\x1a\x16.session_service.Token\"\x00\x12G\n" +
	"\vVerifyToken\x12\x16.session_service.Token\x1a\x1e.session_service.VerifiedToken\"\x00\x12E\n" +
	"\rCreateSession\x12\x18.session_service.Session\x1a\x18.session_service.Session\"\x00\x12I\n" +
	"\x12GetSessionByUserID\x12\x17.session_service.UserID\x1a\x18.session_service.Session\"\x00B4Z2github.com/Abelova-Grupa/Mercypher/proto/sessionpbb\x06proto3"

var (
	file_session_session_service_proto_rawDescOnce sync.Once
	file_session_session_service_proto_rawDescData []byte
)

func file_session_session_service_proto_rawDescGZIP() []byte {
	file_session_session_service_proto_rawDescOnce.Do(func() {
		file_session_session_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_session_service_proto_rawDesc), len(file_session_session_service_proto_rawDesc)))
	})
	return file_session_session_service_proto_rawDescData
}

var file_session_session_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_session_session_service_proto_goTypes = []any{
	(*UserID)(nil),                // 0: session_service.UserID
	(*UserLocation)(nil),          // 1: session_service.UserLocation
	(*Token)(nil),                 // 2: session_service.Token
	(*VerifiedToken)(nil),         // 3: session_service.VerifiedToken
	(*LastSeen)(nil),              // 4: session_service.LastSeen
	(*Session)(nil),               // 5: session_service.Session
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_session_session_service_proto_depIdxs = []int32{
	6,  // 0: session_service.LastSeen.Time:type_name -> google.protobuf.Timestamp
	6,  // 1: session_service.Session.ConnectedAt:type_name -> google.protobuf.Timestamp
	1,  // 2: session_service.SessionService.CreateUserLocation:input_type -> session_service.UserLocation
	0,  // 3: session_service.SessionService.GetUserLocation:input_type -> session_service.UserID
	1,  // 4: session_service.SessionService.UpdateUserLocation:input_type -> session_service.UserLocation
	0,  // 5: session_service.SessionService.DeleteUserLocation:input_type -> session_service.UserID
	4,  // 6: session_service.SessionService.CreateLastSeen:input_type -> session_service.LastSeen
	0,  // 7: session_service.SessionService.GetLastSeen:input_type -> session_service.UserID
	4,  // 8: session_service.SessionService.UpdateLastSeen:input_type -> session_service.LastSeen
	0,  // 9: session_service.SessionService.DeleteLastSeen:input_type -> session_service.UserID
	0,  // 10: session_service.SessionService.CreateToken:input_type -> session_service.UserID
	2,  // 11: session_service.SessionService.VerifyToken:input_type -> session_service.Token
	5,  // 12: session_service.SessionService.CreateSession:input_type -> session_service.Session
	0,  // 13: session_service.SessionService.GetSessionByUserID:input_type -> session_service.UserID
	1,  // 14: session_service.SessionService.CreateUserLocation:output_type -> session_service.UserLocation
	1,  // 15: session_service.SessionService.GetUserLocation:output_type -> session_service.UserLocation
	1,  // 16: session_service.SessionService.UpdateUserLocation:output_type -> session_service.UserLocation
	7,  // 17: session_service.SessionService.DeleteUserLocation:output_type -> google.protobuf.Empty
	4,  // 18: session_service.SessionService.CreateLastSeen:output_type -> session_service.LastSeen
	4,  // 19: session_service.SessionService.GetLastSeen:output_type -> session_service.LastSeen
	4,  // 20: session_service.SessionService.UpdateLastSeen:output_type -> session_service.LastSeen
	7,  // 21: session_service.SessionService.DeleteLastSeen:output_type -> google.protobuf.Empty
	2,  // 22: session_service.SessionService.CreateToken:output_type -> session_service.Token
	3,  // 23: session_service.SessionService.VerifyToken:output_type -> session_service.VerifiedToken
	5,  // 24: session_service.SessionService.CreateSession:output_type -> session_service.Session
	5,  // 25: session_service.SessionService.GetSessionByUserID:output_type -> session_service.Session
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_session_session_service_proto_init() }
func file_session_session_service_proto_init() {
	if File_session_session_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_session_service_proto_rawDesc), len(file_session_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_session_service_proto_goTypes,
		DependencyIndexes: file_session_session_service_proto_depIdxs,
		MessageInfos:      file_session_session_service_proto_msgTypes,
	}.Build()
	File_session_session_service_proto = out.File
	file_session_session_service_proto_goTypes = nil
	file_session_session_service_proto_depIdxs = nil
}
