// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: message/message-service.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message doesn't have an id before passing through MessageService
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *ChatMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_message_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *RelayResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_message_message_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{2}
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_message_message_service_proto protoreflect.FileDescriptor

const file_message_message_service_proto_rawDesc = "" +
	"\n" +
	"\x1dmessage/message-service.proto\x12\x0fmessage_service\"\x7f\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"'\n" +
	"\rRelayResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\"+\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId2\xa8\x01\n" +
	"\x0eMessageService\x12H\n" +
	"\vSendMessage\x12\x1c.message_service.ChatMessage\x1a\x1b.message_service.MessageAck\x12L\n" +
	"\fRelayMessage\x12\x1c.message_service.ChatMessage\x1a\x1e.message_service.RelayResponseBGZEgithub.com/Abelova-Grupa/Mercypher/message-service/external/messagepbb\x06proto3"

var (
	file_message_message_service_proto_rawDescOnce sync.Once
	file_message_message_service_proto_rawDescData []byte
)

func file_message_message_service_proto_rawDescGZIP() []byte {
	file_message_message_service_proto_rawDescOnce.Do(func() {
		file_message_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_service_proto_rawDesc), len(file_message_message_service_proto_rawDesc)))
	})
	return file_message_message_service_proto_rawDescData
}

var file_message_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_message_service_proto_goTypes = []any{
	(*ChatMessage)(nil),   // 0: message_service.ChatMessage
	(*RelayResponse)(nil), // 1: message_service.RelayResponse
	(*MessageAck)(nil),    // 2: message_service.MessageAck
}
var file_message_message_service_proto_depIdxs = []int32{
	0, // 0: message_service.MessageService.SendMessage:input_type -> message_service.ChatMessage
	0, // 1: message_service.MessageService.RelayMessage:input_type -> message_service.ChatMessage
	2, // 2: message_service.MessageService.SendMessage:output_type -> message_service.MessageAck
	1, // 3: message_service.MessageService.RelayMessage:output_type -> message_service.RelayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_message_service_proto_init() }
func file_message_message_service_proto_init() {
	if File_message_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_service_proto_rawDesc), len(file_message_message_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_message_service_proto_goTypes,
		DependencyIndexes: file_message_message_service_proto_depIdxs,
		MessageInfos:      file_message_message_service_proto_msgTypes,
	}.Build()
	File_message_message_service_proto = out.File
	file_message_message_service_proto_goTypes = nil
	file_message_message_service_proto_depIdxs = nil
}
