# Builder image for multi stage building
FROM golang:1.25.3-alpine AS builder
WORKDIR /user-docker

# Copying only mod files for caching
COPY go.mod go.sum ./
RUN go mod download

# Copying other project content and building the binary
COPY . .
RUN go build -o main ./cmd/server

FROM alpine:3.20
WORKDIR /user-docker

COPY  --from=builder /user-docker/main . 

EXPOSE 50054

CMD ["./main"]